### PR TITLE
Support other website languages

### PR DESCRIPTION
**Pull request by DominikSLK**
Support other website languages

### CODE REVIEW

**Comment by supercrafter100** [comment]
This still isn’t a reliable way. The language can be changed within the user their own files and GitHub will rate limit me anyways.

In the next namelessmc release, a new webhook type is made which just sends all the suggestion data. This will remove the need to check the embed titles and all that sketchy stuff. 

If it does continue to be an issue, I’ll just require users to make two separate webhooks to different endpoint for the two events. This just removes the issue entirely.

**Comment by supercrafter100** [comment]
Im just going to keep the en_UK restriction in place until the next version is released. That removes a lot of complexity anyways.

as a quick note. I don’t really like the fact that you put methods not related at all to the webserver and more to just interacting with the api within the webserver class. In the future, I’d appreciate it if those are just split up into either their own class or just add it to the suggestionsapi class.

Then one last thing. You only require to modify the en_UK language file if you are changing it. Weblate does the rest and removes it from the other files

**Comment by DominikSLK** [comment]
ok

**Comment by supercrafter100** [comment]
Thanks for at least trying to solve the issue though. The solution you’ve provided will probably work but it’s just a temporary fix and adds more complexity than I’d like.

**Pull request closed without merging**
